{{- if .Values.useStatefulSet }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "game-servers.fullname" . }}-headless
  labels:
    {{- include "game-servers.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "game-servers.selectorLabels" . | nindent 4 }}
  ports:
    {{- range .Values.gameService.ports }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
{{- end }}
